//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount_Type()
        {
            this.Discount_Code = new HashSet<Discount_Code>();
        }
    
        public int DiscountType_ID { get; set; }
        public string DiscountType_Name { get; set; }
        public int Book_Count { get; set; }
        public double DiscountType_Promotion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount_Code> Discount_Code { get; set; }
    }
}
