//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Wage
    {
        public int ID { get; set; }
        public int Employee_ID { get; set; }
        public double Salary { get; set; }
        public System.DateTime Date { get; set; }
        public int SumDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
